### ISSUE TITLE
(Master) Introduction to Digital Media & other classes

### ISSUE THREAD

**Issue by woche1** [digitalmediabremen/hej#25]
Greetings everyone! How come Introduction to Digital Media and Wearable Computing are offered at the same schedule? What choices do we have in the field of Advanced Computer Graphics? See you on orientation week.

**Comment by jelko** [comment]
**Introduction to Digital Media** (IDM) is an introductory class into the programme for all students (MA & MSc). It is super useful to this in the first semester. The interdisciplinary class starts Monday 16. Oct. 14:00 - 18:00 at HfK.

All course offering will be explained at the welcoming next **Tuesday (2017-10-10 11:00) at HfK.**

--

Since it was asked: The Wearable Computing class is also on Mondays 14:00. Therefore it is practically not possible to do visit it this semester. Advanced Computer Graphics is usually thought in the summer semester by Gabriel Zachmann.

If you can't wait until Tuesday: Some of class offerings for [Uni](http://www.uni-bremen.de/en/studies/lecture-courses/course-catalogue.html?tx_hbulvp_pi1%5Bmodule%5D=4132cbe2326f0683415168a687a1e4ab) and [HfK](https://application.hfk-bremen.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-ACAWluw9LDs6zU3O22NUWmP8.rVZ92QQa53aoQDIjxCtJvuOa4ItdUWPI19I0LywOojsXaYqvsWgrTV9kn0-TgXd0CGM439FKSm-m469-UVY6mRoRrozBbdIREDFM6SPPdwIHq..TXWH1MN3T) are already online. (Preliminary)
